### ISSUE TITLE
Remove "Your paste can be seen here:" output

### ISSUE THREAD

**Issue by ManDay** [zlin/wgetpaste#19]
I think this line should be removed or at least omitted unless `--verbose`. It doesn't seem good practice for a simple tool, just as if `cat` wrote "Here is your data:" to `stderr` on every invocation. It would be nice to just be able to run `/exec -o wgetpaste file.txt` in Weechat, too.

**Comment by bcattaneo** [comment]
Thinking about compatibility (maybe someone is already expecting such line and parsing accordingly), maybe it could be a new flag that avoids such line when defined.

**Comment by mjeveritt** [comment]
Maybe a `--quiet` or `--silent` option?

**Comment by ezzieyguywuf** [comment]
I agree the default should be bare output.

**Comment by Cogitri** [comment]
Patches welcome, I suppose

**Comment by nvinson** [comment]
FYI: That message is not printed to the screen if stderr is redirected to a file or /dev/null.
