### ISSUE TITLE
Create release 2.31

### ISSUE THREAD

**Issue by xxc3nsoredxx** [zlin/wgetpaste#27]
Recent commits such as #26 contain important fixes on top of version 2.30. The Gentoo package maintainers don't wish to update the package by applying commits as patches and would rather see a new release ([Bug 740762](https://bugs.gentoo.org/740762) [Bug 788370](https://bugs.gentoo.org/788370)).

Is the current master in a state where a new release could be made so that the updates will propagate into distros's repos?

**Comment by nvinson** [comment]
I don't know about @Cogitri, @bcattaneo, and the others, but I couldn't care less what gentoo's package maintainer wants.

However, I will admit that there have been several updates since 2.30, so a version bump might be a good idea.

**Comment by Cogitri** [comment]
We certainly want to help package maintainers, so tagging a new release would be a good idea. I think before we do that (or accept new feature work), we should look into a simple test suite for wgetpaste that just creates a paste with a test string and then fetches it and asserts it gets the same string back.

**Comment by nvinson** [comment]
@xxc3nsoredxx @mjeveritt In the meantime, you can find the ebuild you're seeking at https://github.com/nvinson/nuntoo/blob/379da4e38ed0f1d03c5246cf7a777c5da609c87b/app-text/wgetpaste/wgetpaste-2.31_pre20210505.ebuild

@Cogitri Do you have a specific test framework in mind?

**Comment by Cogitri** [comment]
Yup, a simple bash script would do the trick, I suppose.

**Comment by xxc3nsoredxx** [comment]
@Cogitri I created a script that does the above

See PR #28
