### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by ShorTie8** [zlin/wgetpaste#34]
This is a great little utility.
Well used in #gentoo on irc.
But the output can be really hard to read at times.
The output is quite hard to read due to the ansi stuff at times.
Was wondering how hard it would be to add the --color=n to the  emerge command.
So it be like,  wgetpaste -ic 'emerge --ask --color=n gnome-base/gnome'.
Instead of wgetpaste -ic 'emerge --ask gnome-base/gnome'

**Comment by xxc3nsoredxx** [comment]
I'm actually working on this right now, but in general (ie, not limited to `emerge` stuff).

**Comment by ShorTie8** [comment]
Cool, Thankz
So it's now -Nic, lol.
Way cool.
