### ISSUE TITLE
dpaste.com is broken when using DNSSEC

### ISSUE THREAD

**Issue by Jturnerusa** [zlin/wgetpaste#36]
dpaste.com does not work correctly with DNSSEC enabled as mentioned in the PR and commit message. A new default service seems like a good idea! 

All of the other services seem to work correctly from my testing. I think bpaste is the most user friendly paste service after dpaste so in the PR I set that to the new default, if this isn't an acceptable default hopefully we can find another one that isn't dpaste.

Thanks!

https://github.com/zlin/wgetpaste/pull/35

**Comment by heirecka** [comment]
Closed via https://github.com/zlin/wgetpaste/pull/35
