### ISSUE TITLE
Support for gitlab snippets

### ISSUE THREAD

**Issue by unode** [zlin/wgetpaste#8]
Gitlab snippets have a [documented API](https://docs.gitlab.com/ee/api/snippets.html).

The API is similar to that of _Gists_ so it should be relatively straightforward to implement it.

**Comment by bcattaneo** [comment]
@unode hey there. Can you give this a try?. Thanks!

**Comment by unode** [comment]
Thanks for the heads up! This works great!

Would perhaps add a short sentence on the required type of Token.
Thanks again.
